name: Test Snake

on: [push]

jobs:
    test:
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v2

            - name: "Setup Go"
              uses: actions/setup-go@v2
              with:
                  go-version: 1.16

            - name: "Execute Test"
              run: go test -v
